version: '3.8'
services:
  java:
    image: openjdk:11
    ports:
      - 8081:8080
    tty: true
    volumes:
      - ./demo:/srv:cached
    working_dir: /srv
    environment:
      - TEST_VAR=TEST_ENV_VAR
    command: /bin/sh -c './boot.sh' 
      